  - alias: Solnedgång
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: group.familjen
      state: home
    action:
  #    - delay: '00:15:00'
      - service: light.turn_on
        entity_id: group.lampor
      - service: light.turn_on
        entity_id: light.xiaomi_philips_smart_led_ball
        data:
          brightness_pct: 100
          transition: 120
          color_name: white

  - alias: "Lampa av soluppgång"
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: light.turn_off
        data:
          entity_id: group.lampor

  - alias: "On nar någon kommer"
    trigger:
      platform: state
      entity_id: group.familjen
      from: 'not_home'
      to: 'home'
    condition:
      condition: and
      conditions:
        - condition: time
          # At least one of the following is required.
          after: '07:00:00'
          before: '23:00:00'
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
    action:
    - data:
        entity_id: group.lampor
      service: light.turn_on

  - alias: "Full belysning vid på 19"
    trigger:
      - platform: state
        entity_id: light.xiaomi_philips_smart_led_ball
        #from: 'off'
        to: 'on'
    condition:
      condition: time
      # At least one of the following is required.
      after: '15:00:00'
      before: '20:30:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          brightness: 255
          color_name: white

  - alias: "Belysning vid på 20"
    trigger:
      - platform: state
        entity_id: light.xiaomi_philips_smart_led_ball
        #from: 'off'
        to: 'on'
    condition:
      condition: time
      # At least one of the following is required.
      after: '20:30:00'
      before: '21:00:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: yellow
          brightness: 255

  - alias: "Belysning vid på 21"
    trigger:
      - platform: state
        entity_id: light.xiaomi_philips_smart_led_ball
        #from: 'off'
        to: 'on'
    condition:
      condition: time
      # At least one of the following is required.
      after: '21:00:00'
      before: '22:00:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: yellow
          brightness: 150

  - alias: "Belysning vid på 22"
    trigger:
      - platform: state
        entity_id: light.xiaomi_philips_smart_led_ball
        #from: 'off'
        to: 'on'
    condition:
      condition: time
      # At least one of the following is required.
      after: '22:00:00'
      before: '23:59:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: orange
          brightness: 100

  - alias: "Lampa Kl19"
    trigger:
      - platform: time_pattern
        hours: '19'
        minutes: '00'
    condition:
      - condition: state
        entity_id: light.xiaomi_philips_smart_led_ball
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: white
          brightness: 255

  - alias: "Lampa Kl20"
    trigger:
      - platform: time_pattern
        hours: '20'
        minutes: '30'
    condition:
      - condition: state
        entity_id: light.xiaomi_philips_smart_led_ball
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: white
          brightness: 255

  - alias: "Lampa Kl21"
    trigger:
      - platform: time_pattern
        hours: '21'
        minutes: '00'
    condition:
      - condition: state
        entity_id: light.xiaomi_philips_smart_led_ball
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: yellow
          brightness: 150

  - alias: "Lampa Kl22"
    trigger:
      - platform: time_pattern
        hours: '22'
        minutes: '00'
    condition:
      - condition: state
        entity_id: light.xiaomi_philips_smart_led_ball
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: orange
          brightness: 100

  - alias: "Lampa Kl23"
    trigger:
      - platform: time_pattern
        hours: '23'
        minutes: '00'
    condition:
      - condition: state
        entity_id: light.xiaomi_philips_smart_led_ball
        state: 'on'
      - condition: state
        entity_id: group.jans
        state: home
    action:
      - service: light.turn_on
        data:
          entity_id: light.xiaomi_philips_smart_led_ball
          transition: 30
          color_name: gold
          brightness: 50

  - alias: "Lampa av"
    trigger:
      - platform: time_pattern
        #hours: '00'
        minutes: '20'
        seconds: '30'
    condition:
      - condition: state
        entity_id: media_player.lg_webos_tv_e207
        state: problem
      - condition: time
        # At least one of the following is required.
        after: '00:00:00'
        before: '05:59:00'
    action:
      - service: light.turn_off
        data:
          entity_id: group.lampor

  - alias: "Lampa av2"
    trigger:
      platform: state
      entity_id: media_player.lg_webos_tv_e207
      from: 'ok'
      to: 'problem'
      for: "00:15:00"
    condition:
      - condition: time
        # At least one of the following is required.
        after: '00:00:00'
        before: '05:59:00'
    action:
      - service: light.turn_off
        data:
          entity_id: group.lampor

  - alias: "Slå av alla lampor om av efter 23"
    trigger:
      - platform: state
        entity_id: light.xiaomi_philips_smart_led_ball
        to: 'unavailable'
    condition:
      condition: time
      # At least one of the following is required.
      after: '23:00:00'
      #before: '23:59:00'
    action:
      - service: light.turn_off
        data:
          entity_id: group.lampor

  - alias: "Slå av alla lampor om min telefon laddas efter 22:30"
    trigger:
      - platform: state
        entity_id: sensor.stf_l09_battery_state
        to: 'charging'
    condition:
      condition: time
      # At least one of the following is required.
      after: '22:30:00'
      #before: '23:59:00'
    action:
      - service: light.turn_off
        data:
          entity_id: group.lampor

  - alias: Tand lampa
    trigger:
      platform: state
      entity_id: binary_sensor.pir_sensor2
      to: 'on'
    action:
      service: light.turn_on
      entity_id: group.lampor
  
  - alias: Slack lampa
    trigger:
      platform: state
      entity_id: binary_sensor.pir_sensor2
      to: 'off'
      for:
        minutes: 2
    action:
      service: light.turn_off
      entity_id: group.lampor

  - alias: "Lyse på morgonen"
    trigger:
      platform: state
      entity_id: binary_sensor.pir_sensor2
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          # At least one of the following is required.
          after: '06:30:00'
          before: '09:00:00'
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
    action:
    - data:
        entity_id: group.lampor
      service: light.turn_on

  - alias: "Lyse på kvallen"
    trigger:
      platform: state
      entity_id: binary_sensor.pir_sensor2
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          # At least one of the following is required.
          after: '14:45:00'
          before: '23:59:00'
        - condition: state
          entity_id: group.lampor
          state: 'off'
        - condition: state
          entity_id: binary_sensor.stf_l09_is_charging
          state: 'off'
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
    action:
    - data:
        entity_id: group.lampor
      service: light.turn_on

  - alias: "Slå på lampor vid solnedgång"
    trigger:
    - event: sunset
      platform: sun
    condition:
    action:
    - data:
        entity_id: light.deltaco_sh_op01
      service: light.turn_on
  
  - alias: "Efter midnatt"
    trigger:
      - at: "00:30:00"
        platform: time
    condition:
    action:
      - service: light.turn_off
        data:
          entity_id: light.deltaco_sh_op01
  
  - alias: "Slå på lampor"
    trigger:
      - at: "06:00:00"
        platform: time
    condition:
      - condition: sun
        before: sunrise
    action:
      - service: light.turn_on
        data:
          entity_id: light.deltaco_sh_op01

  - alias: "Slå av lampor vid soluppgång"
    trigger:
    - event: sunrise
      platform: sun
    condition:
    action:
    - data:
        entity_id: light.deltaco_sh_op01
      service: light.turn_off
  
