esphome:
  name: testesp12
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "jajo"
  password: "Jans-n3tverk"
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.112.185
    gateway: 192.168.112.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testesp12 Fallback Hotspot"
    password: "Y6IRl3CwPuJ0"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

ota:

mqtt:
  broker: 192.168.112.13
  username: homeassistant
  password: jans-ha
  topic_prefix: homeassistant
  birth_message:
  will_message:
  on_message:
    topic: espinnar5/ota_mode
    payload: 'ON'
    then:
      - deep_sleep.prevent: deep_sleep_2
      - logger.log: "OTA_mode disabled, halting deep sleep"

deep_sleep:
  run_duration: 5s
  sleep_duration: 10min
  id: deep_sleep_2

switch:
  - platform: restart
    name: "ESPPinnar5 restart"

i2c:
  sda: 4
  scl: 5
  scan: True

sensor:
  - platform: adc
    pin: A0
    name: "Testesp12 batteri"
    filters:
      - multiply: 5.769

# Example configuration entry
  - platform: htu21d
    temperature:
      name: "Pinnar5 temp"
    humidity:
      name: "Pinnar5 fukt"

